### ISSUE TITLE
Function similar to jQuery UI AutoComplete "Select:"

### ISSUE THREAD

**Issue by sajiddesigner** [agarzola/jQueryAutocompletePlugin#49]
Hello
I have following values returned from source in json format
{id, label}

i have set label to search and autocomplete on field category_label

I have a hidden field called id="cat_id"

I want to set id as value of #cat_id field, if an item is selected from suggestions.
Please confirm how can i do this. I dont want to use jQuery UI Autocomplete as i have an existing project and i need to add categroy id to a hidden field.

**Comment by agarzola** [comment]
Hello, @sajiddesigner.

If I remember correctly, you should be able to provide a result handler like this:
```
$('#your_input_field').autocomplete(data_or_url, {
  // options
}).result(function (event, item) {
  // item.id and item.label should be accessible in here
  $('#cat_id').val(item.id);
});
```

Whenever a result is selected, I believe the above result handler would be invoked.

**Comment by sajiddesigner** [comment]
Hello
Thank you for your support.
It works but if i use datatype:jsonp it does not work.

Here is my code.

`$("#category_title").autocomplete("<?php echo site_url('items/suggest_category');?>",
        
                {  
            dataType: 'jsonp',
            max:100,
            minChars:0,
            delay:10,            
        }
            ).result(function (event, item) {
  // item.id and item.label should be accessible in here
  //item.id
  console.log(item);
          $('#category').val(item.id);
});
`

it is not showing any error,. it is consistently showing loading icon if click or type any thing in text box.  If i access request URL directly then i am getting following output.

`[{"id":"1","title":"Rolls"},{"id":"2","title":"Burgers"},{"id":"3","title":"Sandwich"},{"id":"4","title":"Soft Drinks"},{"id":"5","title":"Kabab"},{"id":"6","title":"Bar B Q"},{"id":"7","title":"Soups"},{"id":"8","title":"Chinese"},{"id":"9","title":"Extras"}]
`

Plz suggest solution.

Thanks

**Comment by agarzola** [comment]
Why do you need this to be JSONP?

**Comment by sajiddesigner** [comment]
I need this to be json.. not jsonp

Actually i need to insert row ID in DB and show row title at frontend. thats why i need this to use Json. In your docs, it says i can use string or jsonp as data type so i used jsonp.

if i use dataType: string then i get following line in field suggestions.

'[{"id":"1","title":"Rolls"},{"id":"2","title":"Burgers"},{"id":"3","title":"Sandwich"},{"id":"4","title":"Soft Drinks"},{"id":"5","title":"Kabab"},{"id":"6","title":"Bar B Q"},{"id":"7","title":"Soups"},{"id":"8","title":"Chinese"},{"id":"9","title":"Extras"}] '

**Comment by sajiddesigner** [comment]
See this 

![image](https://cloud.githubusercontent.com/assets/5917783/18489600/97db4316-7a17-11e6-8129-ee0b719d9738.png)

I want to show titles only and one title in a row.

**Comment by agarzola** [comment]
Have you tried setting `dataType: 'json'`?

**Comment by sajiddesigner** [comment]
hello.,,, yes i have solved this. 

Modfied your example code to match my own . here is my final code.

`
 $("#category_title").autocomplete("<?php echo site_url('items/suggest_category');?>",        
                {  
                    dataType:'json',
                    parse: function(data) {
                   var rows = new Array();
        console.log(data);
        //data = data.title;
        for(var i=0; i<data.length; i++){
            rows[i] = { data:data[i], value:data[i].title, result:data[i].title };
        }
        return rows;
    },
    formatItem: function(row, i, n) {
        return  row.title; //row.id + ', ' +
        },
            max:100,
            minChars:0,
            delay:10,
        } ).result(function (event, item) {
  console.log(item);
          $('#category').val(item.id);
});
`

Thank you for your help.

**Comment by agarzola** [comment]
Excellent! I edited your code formatting a bit to make it easier to read for anyone who might need help with this in the future.

I’m not sure where in the docs you found that the `dataType` is expected to be `'string'` or `'jsonp'`. Could you point to where you saw this, so I can fix it? Better yet, please feel free to clone, fix it, and submit a pull-request. Either way, thanks for pointing it out!

**Comment by sajiddesigner** [comment]
Hello @agarzola  
Thank your for your help. It helped me. Fixed issues.. Thanks.
